# Generated by Django 5.0.7 on 2024-12-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('branch', models.CharField(choices=[('AIDS', 'Artificial Intelligence and Data Science'), ('CSE', 'Computer Science and Engineering'), ('CSIT', 'Computer Science and Information Technology'), ('ECE', 'Electronics and Communication Engineering')], max_length=4)),
                ('year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')])),
                ('training_type', models.CharField(choices=[('Personal Training', 'Personal Training'), ('Club Member', 'Club Member')], max_length=20)),
            ],
        ),
    ]
