# Generated by Django 5.0.7 on 2024-12-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0002_student_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=100, unique=True),
        ),
    ]
