# Generated by Django 5.0.7 on 2024-12-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0003_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[(1, 'B.Com'), (2, 'B.A'), (3, 'B.Arch'), (4, 'B.Com.(Hons)'), (5, 'B.Pharmacy'), (6, 'B.Sc - VC'), (7, 'B.Sc (Animation & Gaming)'), (8, 'B.Sc (Hons.) Agriculture'), (9, 'B.Tech AI&DS'), (10, 'B.Tech CS&IT'), (11, 'B.Tech ECS'), (12, 'B.Tech IOT'), (13, 'BBA'), (14, 'BBA- BA'), (15, 'BBA-LLB'), (16, 'BCA'), (17, 'B.Tech ECE'), (18, 'B.Tech CSE - Regular'), (19, 'B.Tech CSE - Honors'), (20, 'B.Tech BT'), (21, 'B.Tech CE'), (22, 'B.Tech EEE'), (23, 'B.Tech ME'), (24, 'LLB'), (25, 'M.Pharmacy'), (26, 'M.Sc Computational Mathematics'), (27, 'M.Sc Nano Science and Technology'), (28, 'M.Sc Chemistry'), (29, 'M.Sc Physics'), (30, 'M.Tech - EVT'), (31, 'M.Tech - PE & PS'), (32, 'MA DH&LS'), (33, 'MA - English'), (34, 'MBA'), (35, 'MCA'), (36, 'M.Sc - F&C'), (37, 'M.Tech - CTM'), (38, 'M.Tech - Machine Design'), (39, 'M.Tech - SE'), (40, 'M.Tech - Thermal Engineering'), (41, 'M.Tech - CSE'), (42, 'Pharma D')], max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Club Incharge', 'Club Incharge'), ('Report Manager', 'Report Manager'), ('Super Admin', 'Super Admin')], default='Student', max_length=20),
        ),
    ]
