# Generated by Django 5.0.7 on 2024-12-30 13:39
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0005_alter_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('B.Com', 'B.Com'), ('B.A', 'B.A'), ('B.Arch', 'B.Arch'), ('B.Com.(Hons)', 'B.Com.(Hons)'), ('B.Pharmacy', 'B.Pharmacy'), ('B.Sc - VC', 'B.Sc - VC'), ('B.Sc (Animation & Gaming)', 'B.Sc (Animation & Gaming)'), ('B.Sc (Hons.) Agriculture', 'B.Sc (Hons.) Agriculture'), ('B.Tech AI&DS', 'B.Tech AI&DS'), ('B.Tech CS&IT', 'B.Tech CS&IT'), ('B.Tech ECS', 'B.Tech ECS'), ('B.Tech IOT', 'B.Tech IOT'), ('BBA', 'BBA'), ('BBA- BA', 'BBA- BA'), ('BBA-LLB', 'BBA-LLB'), ('BCA', 'BCA'), ('B.Tech ECE', 'B.Tech ECE'), ('B.Tech CSE - Regular', 'B.Tech CSE - Regular'), ('B.Tech CSE - Honors', 'B.Tech CSE - Honors'), ('B.Tech BT', 'B.Tech BT'), ('B.Tech CE', 'B.Tech CE'), ('B.Tech EEE', 'B.Tech EEE'), ('B.Tech ME', 'B.Tech ME'), ('LLB', 'LLB'), ('M.Pharmacy', 'M.Pharmacy'), ('M.Sc Computational Mathematics', 'M.Sc Computational Mathematics'), ('M.Sc Nano Science and Technology', 'M.Sc Nano Science and Technology'), ('M.Sc Chemistry', 'M.Sc Chemistry'), ('M.Sc Physics', 'M.Sc Physics'), ('M.Tech - EVT', 'M.Tech - EVT'), ('M.Tech - PE & PS', 'M.Tech - PE & PS'), ('MA DH&LS', 'MA DH&LS'), ('MA - English', 'MA - English'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('M.Sc - F&C', 'M.Sc - F&C'), ('M.Tech - CTM', 'M.Tech - CTM'), ('M.Tech - Machine Design', 'M.Tech - Machine Design'), ('M.Tech - SE', 'M.Tech - SE'), ('M.Tech - Thermal Engineering', 'M.Tech - Thermal Engineering'), ('M.Tech - CSE', 'M.Tech - CSE'), ('Pharma D', 'Pharma D')],null=False),
        ),
    ]
