# Generated by Django 5.0.7 on 2024-12-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0006_alter_student_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
    ]
