# Generated by Django 5.0.7 on 2024-12-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0008_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('AIDS', 'Artificial Intelligence and Data Science'), ('CSE', 'Computer Science and Engineering'), ('CSIT', 'Computer Science and Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering')], default='AIDS', max_length=4),
        ),
    ]
