# Generated by Django 5.0.7 on 2024-12-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0012_student_cluster_student_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='girls_hostel',
            field=models.CharField(blank=True, choices=[('', 'Select Girls Hostel'), ('Kanchana Ganga Hostel', 'Kanchana Ganga Hostel'), ('Himalaya Girls Hostel', 'Himalaya Girls Hostel'), ('Outside Hostel', 'Outside Hostel')], max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_boys_campus',
            field=models.CharField(blank=True, choices=[('', 'Select one'), ('in campus', 'in campus'), ('outside campus', 'outside campus')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_boys_in_campus',
            field=models.CharField(blank=True, choices=[('', 'Select Hostel'), ('Tulip Residency', 'Tulip Residency'), ('Aravali & Vindhya', 'Aravali & Vindhya'), ('Kailash Residency', 'Kailash Residency')], max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_boys_outside_campus',
            field=models.CharField(blank=True, choices=[('', 'Select Hostel'), ('Tirumala', 'Tirumala'), ('Sahyadri', 'Sahyadri'), ('Satpura', 'Satpura'), ('Nilagiri', 'Nilagiri'), ('Archies', 'Archies'), ('Malabar', 'Malabar')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transport',
            field=models.CharField(blank=True, choices=[('', 'Select Transport'), ('College Bus', 'College Bus'), ('Own transport', 'Own transport'), ('Other', 'Other')], max_length=15, null=True),
        ),
    ]
