# Generated by Django 5.0.7 on 2024-12-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0013_student_girls_hostel_student_hostel_boys_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus_route',
            field=models.CharField(blank=True, choices=[('', 'Select Bus Route'), ('8A', 'Bus 8A - Gorantla, Guntur'), ('8B', 'Bus 8B - Lodge Center, Guntur'), ('8C', 'Bus 8C - SVN Colony, Guntur'), ('8D', 'Bus 8D - Golden Gym, Guntur'), ('8E', 'Bus 8E - Kortipadu, Guntur'), ('8F', 'Bus 8F - Hanumaiah Company, Guntur'), ('8G', 'Bus 8G - Seetharamaiah School, Guntur'), ('8H', 'Bus 8H - Stambala Garuvu, Guntur'), ('8I', 'Bus 8I - Vengalayapalem, Guntur'), ('8J', 'Bus 8J - Housing Board, Guntur'), ('8K', 'Bus 8K - Bus Stand, Guntur'), ('8L', 'Bus 8L - Bus Stand, Guntur'), ('8M', 'Bus 8M - Padmaja Petrol Bunk, Guntur'), ('8N', 'Bus 8N - Hanumaiah Company, Guntur'), ('9A', 'Bus 9A - Chinaravuri Park, Tenali'), ('9B', 'Bus 9B - Montissori, Tenali'), ('9C', 'Bus 9C - Angalakuduru, Tenali'), ('9DE', 'Bus 9DE - Bus Stand, Tenali'), ('8T', 'Bus 8T - Thulluru'), ('1A', 'Bus 1A - Vuyyur, Vijayawada'), ('1B', 'Bus 1B - Kankipadu, Vijayawada'), ('1C', 'Bus 1C - Penamalluru, Vijayawada'), ('1D', 'Bus 1D - Tadigadapa, Vijayawada'), ('1E', 'Bus 1E - Time Hospital, Vijayawada'), ('1F', 'Bus 1F - Autonagar Gate, Vijayawada'), ('1G', 'Bus 1G - Patamata, Vijayawada'), ('2A', 'Bus 2A - ESI Bus Stop, Vijayawada'), ('3AB', 'Bus 3AB - ITI Bus Stop, Vijayawada'), ('4A', 'Bus 4A - Gannavaram, Vijayawada'), ('4B', 'Bus 4B - Enikepadu, Vijayawada'), ('4C', 'Bus 4C - Ramavarapadu, Vijayawada'), ('4D', 'Bus 4D - Bank Colony, Vijayawada'), ('5A', 'Bus 5A - MG Road, Vijayawada'), ('6A', 'Bus 6A - Payakapuram, Vijayawada'), ('6B', 'Bus 6B - Ajit Singh Nagar, Vijayawada'), ('6C', 'Bus 6C - Raghavendra Theatre, Vijayawada'), ('6D1', 'Bus 6D1 - Prabhas College, Vijayawada'), ('6E', 'Bus 6E - Food Junction, Vijayawada'), ('6F', 'Bus 6F - Madhura Nagar, Vijayawada'), ('7A', 'Bus 7A - Ibrahimpatnam, Vijayawada'), ('7B', 'Bus 7B - Ibrahimpatnam, Vijayawada'), ('7C', 'Bus 7C - Ibrahimpatnam, Vijayawada'), ('7D', 'Bus 7D - Ibrahimpatnam, Vijayawada'), ('7E', 'Bus 7E - Ibrahimpatnam, Vijayawada'), ('7F', 'Bus 7F - Sivalayam, Vijayawada'), ('7G', 'Bus 7G - Sitara, Vijayawada')], max_length=15, null=True),
        ),
    ]
