# Generated by Django 5.0.7 on 2024-12-25 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubIncharge', '0001_initial'),
        ('Student', '0001_initial'),
        ('SuperAdmin', '0003_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ClubIncharge.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.student')),
            ],
            options={
                'unique_together': {('event', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
