# Generated by Django 5.0.7 on 2024-12-25 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SuperAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('event_poster', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
                ('max_participants', models.PositiveIntegerField(default=0)),
                ('event_incharge', models.ForeignKey(
                    blank=True, 
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    related_name='managed_events', 
                    to='SuperAdmin.student',
                    limit_choices_to={'role': 'Club Incharge'}
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
